### ISSUE TITLE
Portfolio: application deploy

### ISSUE THREAD

**Issue by Sparktan24** [Sparktan24/Portfolio#6]
# Portfolio: application deploy

**Project requirements:**

- Deploy your website using GitHub Pages.
- Check the online version of your portfolio and make sure that the page works properly.
- Update the README of your repository to include a link to the online version.

link to live page: https://sparktan24.github.io/Portfolio/

For detailed info visit: https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/5_deploy.md

**Comment by aimalamiri** [comment]
Hi @Sparktan24, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Untitled](https://user-images.githubusercontent.com/34779928/191327241-37f74da6-10dd-4744-b917-f93ab416cae3.png)

## Invalid Code Review Request

You submitted an issue instead of a pull request, please make sure to submit a pull request for the next review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Sparktan24** [comment]
Hi, @aimalamiri, my code is merged to the main branch, do I need to create a new one to make the PR?

**Comment by aimalamiri** [comment]
You can try updating the README file, it's part of the project requirements.
